main:
  push:
    - imports: https://cnb.cool/M.L/wave-secrets/-/blob/main/env.yml
      docker:
        image: node:22
      stages:
        - name: migrate and deploy to Cloudflare Workers
          script: |
            npm ci
            CLOUDFLARE_API_TOKEN=$CLOUDFLARE_WORKER_APIKEY npx wrangler d1 migrations apply zmu-proj-d1 --remote
            CLOUDFLARE_API_TOKEN=$CLOUDFLARE_WORKER_APIKEY npm run deploy
