main:
  push:
    - imports: https://cnb.cool/M.L/wave-secrets/-/blob/main/env.yml
      docker:
        image: node:22
      stages:
        - name: deploy to Cloudflare Workers
          script: |
            npm install wrangler
            CLOUDFLARE_API_TOKEN=$CLOUDFLARE_WORKER_APIKEY npx wrangler deploy
